[pytest]
addopts = -v --tb=short --html=reports/report.html --self-contained-html
markers =
    smoke: быстрые проверки основного функционала
    regression: регрессионные проверки
    ui: проверки пользовательского интерфейса
    search: проверки поиска YouTube
    video: проверки страницы просмотра видео
python_files = test_*.py
python_classes = Test*
python_functions = test_*
